# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  EngineCore_config = debug_x64
  GLFW_config = debug_x64
  Glad_config = debug_x64
  ImGui_config = debug_x64
  Blackbird_config = debug_x64
  Sandbox_config = debug_x64

else ifeq ($(config),release_x64)
  EngineCore_config = release_x64
  GLFW_config = release_x64
  Glad_config = release_x64
  ImGui_config = release_x64
  Blackbird_config = release_x64
  Sandbox_config = release_x64

else ifeq ($(config),dist_x64)
  EngineCore_config = dist_x64
  GLFW_config = dist_x64
  Glad_config = dist_x64
  ImGui_config = dist_x64
  Blackbird_config = dist_x64
  Sandbox_config = dist_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := EngineCore GLFW Glad ImGui Blackbird Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui

EngineCore:
ifneq (,$(EngineCore_config))
	@echo "==== Building EngineCore ($(EngineCore_config)) ===="
	@${MAKE} --no-print-directory -C EngineCore -f Makefile config=$(EngineCore_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/imgui -f Makefile config=$(ImGui_config)
endif

Blackbird: EngineCore GLFW Glad ImGui
ifneq (,$(Blackbird_config))
	@echo "==== Building Blackbird ($(Blackbird_config)) ===="
	@${MAKE} --no-print-directory -C Blackbird -f Makefile config=$(Blackbird_config)
endif

Sandbox: EngineCore Blackbird
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C EngineCore -f Makefile clean
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Blackbird/Dependencies/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Blackbird -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo "  dist_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   EngineCore"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   Blackbird"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"